include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true  # Asegura que todas las funciones tengan un tipo de retorno explícito.
    prefer_final_locals: true            # Promueve el uso de 'final' en las variables locales cuando no cambian.
    prefer_const_constructors: true     # Fomenta el uso de constructores 'const' cuando sea posible.
    prefer_single_quotes: true          # Recomienda el uso de comillas simples en lugar de comillas dobles para cadenas de texto.
    avoid_function_literals_in_foreach_calls: true  # Evita el uso de literales de función dentro de llamadas 'forEach' (mejora la legibilidad).
    avoid_escaping_inner_quotes: true   # Evita el uso innecesario de comillas escapadas dentro de cadenas de texto.
    avoid_dynamic_calls: true           # Desaconseja el uso de llamadas 'dynamic', mejor usar tipos concretos para mantener el código tipado y seguro.
    prefer_is_empty: true               # Usa '.isEmpty' en lugar de comprobar 'length == 0' en colecciones.
    unnecessary_new: true               # Elimina el uso innecesario de la palabra clave 'new' al crear objetos (desde Dart 2 ya no es necesario).
    prefer_typing_uninitialized_variables: true  # Asegura que las variables no inicializadas tengan un tipo explícito.
    prefer_constructors_in_immutables: true  # Recomienda usar constructores en clases inmutables (aquellas con campos 'final').
